# Generated by Django 5.0 on 2024-01-20 13:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Designates the latitude of the post.', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Designates the longitude of the post.', max_digits=9, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Coordinates',
                'verbose_name_plural': 'Coordinates',
                'db_table': 'reports_coordinates',
            },
        ),
        migrations.CreateModel(
            name='PostObservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, help_text='Designates the size of the Crown-of-Thorns Starfish at the moment the post taken.', max_length=150, null=True, verbose_name='Size')),
                ('depth', models.CharField(blank=True, help_text='Designates the depth of the Crown-of-Thorns Starfish at the moment the post taken.', max_length=150, null=True, verbose_name='Depth')),
                ('density', models.CharField(blank=True, help_text='Designates the density of the Crown-of-Thorns Starfish at the moment the post taken.', max_length=150, null=True, verbose_name='Density')),
                ('weather', models.CharField(blank=True, help_text='Designates the weather at the moment the post taken.', max_length=150, null=True, verbose_name='Weather')),
            ],
            options={
                'verbose_name': 'Post Observations',
                'verbose_name_plural': 'Posts Observations',
                'db_table': 'reports_post_observations',
            },
        ),
        migrations.CreateModel(
            name='PostStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=False, help_text='Designates that the post can be pinned into the contributors site.', verbose_name='Valid Status')),
                ('is_invalid', models.BooleanField(default=False, help_text='Designates that the post cannot be pinned into the contributors site.', verbose_name='Invalid Status')),
                ('is_uncertain', models.BooleanField(default=False, help_text='Designates that the post is under review to be pinned into the contributors site.', verbose_name='Uncertain Status')),
            ],
            options={
                'verbose_name': 'Post Status',
                'verbose_name_plural': 'Posts Status',
                'db_table': 'reports_post_status',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Designates the description of the post.', max_length=1500, null=True, verbose_name='Description')),
                ('capture_date', models.DateTimeField(default=datetime.datetime(2024, 1, 20, 21, 40, 15, 503040), help_text='Designates the capture date and time of the post.', verbose_name='Capture Date')),
                ('post_photo', models.ImageField(blank=True, default='posts/default.png', help_text='Designates the photo of the post.', null=True, upload_to='posts', verbose_name='Post Photo')),
                ('coordinates', models.ForeignKey(blank=True, help_text='Designates the foreign field of the Coordinates model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.coordinates', verbose_name='Coordinates')),
                ('user', models.ForeignKey(blank=True, help_text='Designates the foreign field of the User model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentications.user', verbose_name='User')),
                ('post_observations', models.ForeignKey(blank=True, help_text='Designates the foreign field of the Post Observations model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.postobservations', verbose_name='Post Observations')),
                ('post_status', models.ForeignKey(blank=True, default=1, help_text='Designates the foreign field of the Post Status model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.poststatus', verbose_name='Post Status')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'reports_post',
            },
        ),
    ]
