# Generated by Django 5.0 on 2024-03-27 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='capture_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 27, 11, 41, 39, 696144), help_text='Designates the capture date and time of the post.', verbose_name='Capture Date'),
        ),
    ]
