# Generated by Django 5.0.4 on 2024-06-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_alter_user_joined_date'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='validated_by',
        ),
        migrations.AddField(
            model_name='post',
            name='validator',
            field=models.ForeignKey(blank=True, help_text='Designates the validator the post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validator', to='authentications.user', verbose_name='Validator'),
        ),
    ]
