# Generated by Django 5.0.4 on 2024-05-01 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.AlterField(
            model_name='post',
            name='capture_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 20, 1, 47, 325035), help_text='Designates the capture date and time of the post.', verbose_name='Capture Date'),
        ),
    ]
