# Generated by Django 5.0.4 on 2024-06-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_post_validated_by_post_validator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='description',
        ),
        migrations.AlterField(
            model_name='depth',
            name='depth',
            field=models.CharField(max_length=65, null=True, verbose_name='Depth'),
        ),
        migrations.AlterField(
            model_name='depth',
            name='description',
            field=models.TextField(default='Default Description', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='size',
            name='description',
            field=models.TextField(default='Default Description', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=65, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather',
            field=models.CharField(max_length=65, null=True, verbose_name='Weather'),
        ),
    ]
