# Generated by Django 5.0.4 on 2024-05-05 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_post_location_alter_post_capture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, help_text='Designates the address of the location.', max_length=150, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='post',
            name='capture_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 49, 53, 407552), help_text='Designates the capture date and time of the post.', verbose_name='Capture Date'),
        ),
    ]
