# Generated by Django 5.0.4 on 2024-06-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_weather_description_alter_depth_depth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contrib_read_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='contrib_read_status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='read_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='read_status',
        ),
    ]
