# Generated by Django 5.0.4 on 2024-06-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_post_contrib_read_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depth',
            name='depth',
            field=models.CharField(max_length=65, null=True, unique=True, verbose_name='Depth'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=65, null=True, unique=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather',
            field=models.CharField(max_length=65, null=True, unique=True, verbose_name='Weather'),
        ),
    ]
