# Generated by Django 5.0.4 on 2024-05-09 05:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0005_alter_intervention_intervention_date_and_more'),
        ('reports', '0005_alter_post_capture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Designates the foreign key of the Address model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='managements.location', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='post',
            name='capture_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 13, 43, 18, 316594), help_text='Designates the capture date and time of the post.', verbose_name='Capture Date'),
        ),
    ]
