# Generated by Django 5.0.6 on 2024-07-05 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0006_alter_barangay_barangay_name_and_more'),
        ('reports', '0005_alter_depth_depth_alter_size_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depth',
            name='depth',
            field=models.CharField(error_messages={'unique': 'This depth already exist.'}, max_length=65, null=True, unique=True, verbose_name='Depth'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(help_text='Designates the foreign key of the Location model.', on_delete=django.db.models.deletion.CASCADE, to='managements.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(error_messages={'unique': 'This size already exist.'}, max_length=65, null=True, unique=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather',
            field=models.CharField(error_messages={'unique': 'This weather already exist.'}, max_length=65, null=True, unique=True, verbose_name='Weather'),
        ),
    ]
