# Generated by Django 5.0.4 on 2024-05-12 12:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0006_alter_intervention_intervention_date_and_more'),
        ('reports', '0006_post_address_alter_post_capture_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='address',
        ),
        migrations.AlterField(
            model_name='post',
            name='capture_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 20, 42, 32, 694072), help_text='Designates the capture date and time of the post.', verbose_name='Capture Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Designates the foreign key of the Location model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='managements.location', verbose_name='Location'),
        ),
    ]
