# Generated by Django 5.0.4 on 2024-05-16 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_post_capture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 15, 14, 28, 540149), help_text='Designates the creation date and time of the post.', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='capture_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 15, 14, 28, 540149), help_text='Designates the capture date and time of the post.', verbose_name='Capture Date'),
        ),
    ]
