# Generated by Django 5.0.4 on 2024-05-19 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0013_alter_user_joined_date'),
        ('reports', '0011_post_contrib_read_date_post_contrib_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='Designates the user who validated the post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_posts', to='authentications.user', verbose_name='Validated By'),
        ),
    ]
