# Generated by Django 5.0.6 on 2024-07-18 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0006_alter_barangay_barangay_name_and_more'),
        ('reports', '0011_alter_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Designates the foreign key of the Location model.', on_delete=django.db.models.deletion.CASCADE, to='managements.location', verbose_name='Location'),
        ),
    ]
