# Generated by Django 5.0.6 on 2024-07-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_alter_post_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Density',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.CharField(error_messages={'unique': 'This Density already exist.'}, max_length=65, null=True, unique=True, verbose_name='Density')),
                ('description', models.TextField(default='Default Description', max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Density',
                'verbose_name_plural': 'Density',
                'db_table': 'reports_density',
            },
        ),
        migrations.AlterField(
            model_name='postobservation',
            name='weather',
            field=models.CharField(error_messages={'unique': 'This weather already exist.'}, max_length=65, null=True, unique=False, verbose_name='Weather'),
        ),
        migrations.RemoveField(
            model_name='postobservation',
            name='density',
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
