# Generated by Django 5.0.6 on 2024-07-21 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_density_alter_postobservation_weather_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postobservation',
            name='weather',
        ),
    ]
