# Generated by Django 5.0.6 on 2024-07-21 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_remove_postobservation_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='postobservation',
            name='density',
            field=models.ForeignKey(blank=True, help_text='Designates the foreign key of the Density model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.density', verbose_name='Density'),
        ),
        migrations.AddField(
            model_name='postobservation',
            name='weather',
            field=models.CharField(error_messages={'unique': 'This weather already exist.'}, max_length=65, null=True, unique=True, verbose_name='Weather'),
        ),
    ]
