# Generated by Django 5.0.6 on 2024-06-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_post_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depth',
            options={'verbose_name': 'Depth', 'verbose_name_plural': 'Depth'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Size', 'verbose_name_plural': 'Size'},
        ),
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name': 'Weather', 'verbose_name_plural': 'Weather'},
        ),
    ]
