# Generated by Django 5.0.6 on 2024-07-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_postobservation_density_postobservation_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postobservation',
            name='weather',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='Weather'),
        ),
    ]
