# Generated by Django 5.0.4 on 2024-06-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_remove_depth_is_deep_remove_depth_is_moderate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(help_text='Designates the size.', max_length=65, null=True, verbose_name='Size'),
        ),
    ]
