# Generated by Django 5.0.6 on 2025-03-07 04:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0022_alter_badge_badge_icon_alter_badge_badge_name_and_more'),
        ('managements', '0008_remove_status_intervention_alter_location_options_and_more'),
        ('reports', '0016_alter_postobservation_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='density',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='depth',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='capture_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Capture Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='coordinates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.coordinates', verbose_name='Coordinates'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='managements.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.postobservation', verbose_name='Post Observation'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_photos',
            field=models.ManyToManyField(blank=True, through='reports.PostGallery', to='reports.postphoto', verbose_name='Post Photos'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='reports.poststatus', verbose_name='Post Status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentications.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validator', to='authentications.user', verbose_name='Validator'),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='post_photos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.postphoto', verbose_name='Post Photo'),
        ),
        migrations.AlterField(
            model_name='postobservation',
            name='density',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.density', verbose_name='Density'),
        ),
        migrations.AlterField(
            model_name='postobservation',
            name='depth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.depth', verbose_name='Depth'),
        ),
        migrations.AlterField(
            model_name='postobservation',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.size', verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='postphoto',
            name='post_photo',
            field=models.ImageField(default='posts/default.png', null=True, upload_to='posts', verbose_name='Post Photo'),
        ),
        migrations.AlterField(
            model_name='poststatus',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Draft'),
        ),
        migrations.AlterField(
            model_name='poststatus',
            name='is_invalid',
            field=models.BooleanField(default=False, verbose_name='Invalid'),
        ),
        migrations.AlterField(
            model_name='poststatus',
            name='is_pending',
            field=models.BooleanField(default=False, verbose_name='Pending'),
        ),
        migrations.AlterField(
            model_name='poststatus',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Valid'),
        ),
        migrations.AlterField(
            model_name='size',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Description'),
        ),
    ]
