# Generated by Django 5.0 on 2024-03-07 13:00

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(blank=True, help_text='Designates the name of the barangay.', max_length=65, null=True, verbose_name='Barangay')),
                ('municipality', models.CharField(blank=True, help_text='Designates the name of the municipality.', max_length=65, null=True, verbose_name='Municipality')),
                ('perimeters', models.TextField(blank=True, help_text='Designates the perimeters of the location.', max_length=15000, null=True, verbose_name='Perimeters')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'managements_location',
            },
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_critical', models.BooleanField(default=False, help_text='Designates that the status is critical.', verbose_name='Critical Status')),
                ('is_moderate', models.BooleanField(default=False, help_text='Designates that the status is moderate.', verbose_name='Moderate Status')),
                ('is_low', models.BooleanField(default=False, help_text='Designates that the status is low.', verbose_name='Low Status')),
            ],
            options={
                'verbose_name': 'Status Type',
                'verbose_name_plural': 'Status Types',
                'db_table': 'managements_status_type',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Designates the title of the intervention.', max_length=150, verbose_name='Title')),
                ('caught_amount', models.IntegerField(blank=True, help_text='Designates the amount of the caught Crown-of-Thorns Starfish at the moment the intervention took place.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Caught Amount')),
                ('details', models.TextField(help_text='Designates the details of the intervention.', max_length=5000, null=True, verbose_name='Details')),
                ('hosting_agency', models.CharField(help_text='Designates the name of the hosting agency.', max_length=150, unique=True, verbose_name='Hosting Agency')),
                ('intervention_photo', models.ImageField(blank=True, default='interventions/default.png', help_text='Designates the photo of the intervention.', null=True, upload_to='interventions', verbose_name='Intervention Photo')),
                ('intervention_date', models.DateField(default=datetime.date(2024, 3, 7), help_text='Designates the date of the intervention.', verbose_name='Intervention Date')),
                ('location', models.ForeignKey(blank=True, help_text='Designates the foreign key of the Location model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='managements.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'db_table': 'managements_intervention',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caught_overall', models.IntegerField(blank=True, help_text='Designates the overall amount of the caught Crown-of-Thorns Starfish at the moment.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Caught Amount')),
                ('onset_date', models.DateField(default=datetime.date(2024, 3, 7), help_text='Designates the onset date of the outbreak status.', verbose_name='Onset Date')),
                ('location', models.ForeignKey(blank=True, help_text='Designates the foreign key of the Location model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='managements.location', verbose_name='Location')),
                ('statustype', models.ForeignKey(blank=True, help_text='Designates the foreign key of the Status Type model.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='managements.statustype', verbose_name='Status Type')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'db_table': 'managements_status',
            },
        ),
    ]
