# Generated by Django 5.0 on 2024-02-25 10:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purok', models.CharField(blank=True, help_text='Designates the name of the purok.', max_length=65, null=True, verbose_name='Purok')),
                ('barangay', models.CharField(blank=True, help_text='Designates the name of the barangay.', max_length=65, null=True, verbose_name='Barangay')),
                ('municipality', models.CharField(blank=True, help_text='Designates the name of the municipality.', max_length=65, null=True, verbose_name='Municipality')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'managements_location',
            },
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_critical', models.BooleanField(default=False, help_text='Designates that the status is critical.', verbose_name='Critical Status')),
                ('is_moderate', models.BooleanField(default=False, help_text='Designates that the status is moderate.', verbose_name='Moderate Status')),
                ('is_low', models.BooleanField(default=False, help_text='Designates that the status is low.', verbose_name='Low Status')),
            ],
            options={
                'verbose_name': 'Status Type',
                'verbose_name_plural': 'Status Types',
                'db_table': 'managements_status_type',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Designates the description of the COTS status.', max_length=1500, null=True, verbose_name='Description')),
                ('onset_date', models.DateTimeField(default=datetime.datetime(2024, 2, 25, 18, 45, 6, 862435), help_text='Designates the onset date of the outbreak status.', verbose_name='Status Date')),
                ('location', models.ForeignKey(blank=True, help_text='Designates the foreign key of the Location model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='managements.location', verbose_name='Location')),
                ('statustype', models.ForeignKey(blank=True, help_text='Designates the foreign key of the Status Type model.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='managements.statustype', verbose_name='Status Type')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'db_table': 'managements_status',
            },
        ),
    ]
