# Generated by Django 5.0.4 on 2024-05-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Designates the latitude of the location.', max_digits=27, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Designates the longitude of the location.', max_digits=27, null=True, verbose_name='Longitude'),
        ),
    ]
