# Generated by Django 5.0 on 2024-03-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustype',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Designates that the status is critical.', verbose_name='Critical'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='is_low',
            field=models.BooleanField(default=False, help_text='Designates that the status is low.', verbose_name='Low'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='is_moderate',
            field=models.BooleanField(default=False, help_text='Designates that the status is moderate.', verbose_name='Moderate'),
        ),
    ]
