# Generated by Django 5.0.4 on 2024-06-24 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_alter_location_latitude_alter_location_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Barangay Perimeters and Default Coordinates', 'verbose_name_plural': 'Barangay Perimeters and Default Coordinates'},
        ),
        migrations.AlterModelOptions(
            name='statustype',
            options={'verbose_name': 'Infestation Level', 'verbose_name_plural': 'Infestation Level'},
        ),
        migrations.AddField(
            model_name='statustype',
            name='description',
            field=models.TextField(default='Default Description', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='barangay_name',
            field=models.CharField(max_length=65, unique=True, verbose_name='Barangay Name'),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.municipality', verbose_name='Municipality Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='barangay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='managements.barangay', verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=27, verbose_name='Default Pin Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=27, verbose_name='Default Pin Longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.municipality', verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='location',
            name='perimeters',
            field=models.TextField(verbose_name='Barangay Perimeter'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='municipality_name',
            field=models.CharField(max_length=65, unique=True, verbose_name='Municipality Name'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='statustype',
            field=models.CharField(default='None', max_length=65, null=True, verbose_name='Infestation Level'),
        ),
    ]
