# Generated by Django 5.0.4 on 2024-06-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0003_alter_location_options_alter_statustype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustype',
            name='statustype',
            field=models.CharField(default='None', max_length=65, null=True, unique=True, verbose_name='Infestation Level'),
        ),
    ]
