# Generated by Django 5.0.4 on 2024-05-19 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0004_alter_intervention_intervention_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='intervention_date',
            field=models.DateField(default=datetime.date(2024, 5, 19), help_text='Designates the date of the intervention.', verbose_name='Intervention Date'),
        ),
        migrations.AlterField(
            model_name='status',
            name='onset_date',
            field=models.DateField(default=datetime.date(2024, 5, 19), help_text='Designates the onset date of the outbreak status.', verbose_name='Onset Date'),
        ),
    ]
