# Generated by Django 5.0.6 on 2024-07-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0005_alter_announcement_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='barangay_name',
            field=models.CharField(error_messages={'unique': 'This barangay already exist.'}, max_length=65, unique=True, verbose_name='Barangay Name'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='municipality_name',
            field=models.CharField(error_messages={'unique': 'This municipality already exist.'}, max_length=65, unique=True, verbose_name='Municipality Name'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='statustype',
            field=models.CharField(default='None', error_messages={'unique': 'This infestation level already exist.'}, max_length=65, null=True, unique=True, verbose_name='Infestation Level'),
        ),
    ]
