# Generated by Django 5.0.4 on 2024-05-26 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0007_alter_intervention_intervention_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='volunteer_amount',
            field=models.IntegerField(blank=True, help_text='Designates the overall amount of the volunteers at the moment the intervention took place.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volunteer Overall'),
        ),
        migrations.AlterField(
            model_name='status',
            name='caught_overall',
            field=models.IntegerField(help_text='Designates the overall amount of the caught Crown-of-Thorns Starfish at the moment.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Caught Overall'),
        ),
    ]
