# Generated by Django 5.0.6 on 2025-03-07 04:57

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0022_alter_badge_badge_icon_alter_badge_badge_name_and_more'),
        ('managements', '0007_alter_intervention_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='intervention',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Location'},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='release_date',
        ),
        migrations.AddField(
            model_name='announcement',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcement_photo',
            field=models.ImageField(default='announcements/default.png', null=True, upload_to='announcements', verbose_name='Announcement Photo'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='context',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='hosting_agency',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Hosting Agency'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managements.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentications.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='status',
            name='caught_overall',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Caught Overall'),
        ),
        migrations.AlterField(
            model_name='status',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='status',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='status',
            name='onset_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Onset Date'),
        ),
        migrations.AlterField(
            model_name='status',
            name='statustype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.statustype', verbose_name='Status Type'),
        ),
        migrations.AlterField(
            model_name='status',
            name='volunteer_overall',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volunteer Overall'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='statustype',
            field=models.CharField(error_messages={'unique': 'This infestation level already exist.'}, max_length=65, null=True, unique=True, verbose_name='Infestation Level'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosting_agency', models.CharField(max_length=150, verbose_name='Hosting Agency')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('details', models.TextField(max_length=5000, verbose_name='Details')),
                ('volunteer_amount', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volunteer Amount')),
                ('caught_amount', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Caught Amount')),
                ('activity_photo', models.ImageField(default='activities/default.png', upload_to='activities', verbose_name='Activity Photo')),
                ('activity_date', models.DateField(default=datetime.date.today, verbose_name='Activity Date')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation Date')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.location', verbose_name='Location')),
                ('statustype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managements.statustype', verbose_name='Status Type')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'managements_activity',
            },
        ),
        migrations.AddField(
            model_name='status',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managements.activity', verbose_name='Activity'),
        ),
        migrations.DeleteModel(
            name='Intervention',
        ),
    ]
