# Generated by Django 5.0.4 on 2024-06-02 03:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0010_alter_intervention_intervention_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='place',
            field=models.CharField(blank=True, help_text='Designates the place of the intervention.', max_length=150, null=True, verbose_name='Place'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='statustype',
            field=models.ForeignKey(blank=True, help_text='Designates the foreign key of the Status Type model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='managements.statustype', verbose_name='Status Type'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='intervention_date',
            field=models.DateField(default=datetime.date(2024, 6, 2), help_text='Designates the date of the intervention.', verbose_name='Intervention Date'),
        ),
        migrations.AlterField(
            model_name='status',
            name='onset_date',
            field=models.DateField(default=datetime.date(2024, 6, 2), help_text='Designates the onset date of the outbreak status.', verbose_name='Onset Date'),
        ),
    ]
