# Generated by Django 5.0.4 on 2024-06-04 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0011_intervention_place_intervention_statustype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='place',
        ),
        migrations.AlterField(
            model_name='intervention',
            name='intervention_date',
            field=models.DateField(default=datetime.date(2024, 6, 4), help_text='Designates the date of the intervention.', verbose_name='Intervention Date'),
        ),
        migrations.AlterField(
            model_name='status',
            name='onset_date',
            field=models.DateField(default=datetime.date(2024, 6, 4), help_text='Designates the onset date of the outbreak status.', verbose_name='Onset Date'),
        ),
    ]
