# Generated by Django 5.0.6 on 2024-06-08 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0012_remove_intervention_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='intervention_date',
            field=models.DateField(default=datetime.date(2024, 6, 8), help_text='Designates the date of the intervention.', verbose_name='Intervention Date'),
        ),
        migrations.AlterField(
            model_name='status',
            name='onset_date',
            field=models.DateField(default=datetime.date(2024, 6, 8), help_text='Designates the onset date of the outbreak status.', verbose_name='Onset Date'),
        ),
    ]
