# Generated by Django 5.0.6 on 2024-06-13 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0013_alter_intervention_intervention_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Location'},
        ),
        migrations.AlterModelOptions(
            name='statustype',
            options={'verbose_name': 'Status Level Type', 'verbose_name_plural': 'Status Level Type'},
        ),
        migrations.AlterField(
            model_name='intervention',
            name='intervention_date',
            field=models.DateField(default=datetime.date(2024, 6, 13), help_text='Designates the date of the intervention.', verbose_name='Intervention Date'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Designates the latitude of the location.', max_digits=27, null=True, verbose_name='Default Pin Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Designates the longitude of the location.', max_digits=27, null=True, verbose_name='Default Pin Longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='perimeters',
            field=models.TextField(blank=True, help_text='Designates the perimeters of the location.', max_length=15000, null=True, verbose_name='Map Perimeters'),
        ),
        migrations.AlterField(
            model_name='status',
            name='onset_date',
            field=models.DateField(default=datetime.date(2024, 6, 13), help_text='Designates the onset date of the outbreak status.', verbose_name='Onset Date'),
        ),
    ]
