# Generated by Django 5.0.4 on 2024-06-16 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0014_alter_location_options_alter_statustype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Designates the creation date and time of the intervention.', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='intervention_date',
            field=models.DateField(default=datetime.date(2024, 6, 16), help_text='Designates the date of the intervention.', verbose_name='Intervention Date'),
        ),
        migrations.AlterField(
            model_name='status',
            name='onset_date',
            field=models.DateField(default=datetime.date(2024, 6, 16), help_text='Designates the onset date of the outbreak status.', verbose_name='Onset Date'),
        ),
    ]
