# Generated by Django 5.0.4 on 2024-06-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0016_remove_statustype_is_critical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustype',
            name='statustype',
            field=models.CharField(default='Critical', help_text='Designates the status type.', max_length=65, null=True, verbose_name='Status Level Type'),
        ),
    ]
