# Generated by Django 5.0.4 on 2024-06-16 06:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0017_alter_statustype_statustype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='caught_amount',
            field=models.IntegerField(blank=True, help_text='Designates the amount of the caught Crown-of-Thorns Starfish at the moment the activity took place.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Caught Amount'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Designates the creation date and time of the activity.', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='details',
            field=models.TextField(help_text='Designates the details of the activity.', max_length=5000, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='intervention_date',
            field=models.DateField(default=datetime.date(2024, 6, 16), help_text='Designates the date of the activity.', verbose_name='Activity Date'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='intervention_photo',
            field=models.ImageField(default='interventions/default.png', help_text='Designates the photo of the activity.', upload_to='interventions', verbose_name='Intervention Photo'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='title',
            field=models.CharField(help_text='Designates the title of the activity.', max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='volunteer_amount',
            field=models.IntegerField(blank=True, help_text='Designates the amount of the volunteers at the moment the activity took place.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volunteer Amount'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='statustype',
            field=models.CharField(default='None', help_text='Designates the status type.', max_length=65, null=True, verbose_name='Status Level Type'),
        ),
    ]
