# Generated by Django 5.0 on 2024-03-27 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 11, 41, 39, 687487), help_text='Designates the joined date and time of the user.', verbose_name='Joined Date'),
        ),
    ]
