# Generated by Django 5.0.4 on 2024-05-01 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 20, 1, 47, 309411), help_text='Designates the joined date and time of the user.', verbose_name='Joined Date'),
        ),
    ]
