# Generated by Django 5.0.4 on 2024-06-23 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_alter_user_joined_date_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='object_id',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 22, 21, 50, 824743), help_text='Designates the joined date and time of the user.', verbose_name='Joined Date'),
        ),
    ]
