# Generated by Django 5.0.4 on 2024-06-24 11:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentications', '0005_rename_created_at_notification_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Last Signin'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=150, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, null=True, to='auth.permission', verbose_name='User Permissions'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='account',
            name='usertype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentications.usertype', verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 19, 12, 25, 952740), help_text='Designates the joined date and time of the user.', verbose_name='Joined Date'),
        ),
    ]
