# Generated by Django 5.0.4 on 2024-06-25 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0006_alter_account_groups_alter_account_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 15, 10, 40, 211168), help_text='Designates the joined date and time of the user.', verbose_name='Joined Date'),
        ),
    ]
