# Generated by Django 5.0.4 on 2024-06-25 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0009_alter_user_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notificationtype',
            field=models.CharField(choices=[('post', 'Post'), ('announcement', 'Announcement'), ('intervention', 'Intervention'), ('post_valid', 'Post Validated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 0, 26, 24, 978007), help_text='Designates the joined date and time of the user.', verbose_name='Joined Date'),
        ),
    ]
