# Generated by Django 5.0.6 on 2024-07-05 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentications', '0010_alter_notification_notificationtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission', verbose_name='User Permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 12, 37, 40, 898771), help_text='Designates the joined date and time of the user.', verbose_name='Joined Date'),
        ),
    ]
