# Generated by Django 5.0.6 on 2024-07-15 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0011_alter_account_groups_alter_account_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 11, 28, 19, 70039), help_text='Designates the joined date and time of the user.', verbose_name='Joined Date'),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='auth_notification',
        ),
    ]
