# Generated by Django 5.0.6 on 2024-07-20 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0012_alter_notification_options_alter_user_joined_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=255)),
                ('badge_icon', models.ImageField(upload_to='badges/')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'db_table': 'user_badge',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notificationtype',
            field=models.CharField(choices=[('post', 'Post'), ('announcement', 'Announcement'), ('intervention', 'Intervention'), ('post_valid', 'Post Validated'), ('achievement', 'Achievement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 11, 23, 8, 40588), help_text='Designates the joined date and time of the user.', verbose_name='Joined Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(blank=True, to='authentications.badge'),
        ),
    ]
