# Generated by Django 5.0.6 on 2024-07-20 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0013_badge_alter_notification_notificationtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 12, 6, 4, 959652), help_text='Designates the joined date and time of the user.', verbose_name='Joined Date'),
        ),
    ]
