# Generated by Django 5.0.4 on 2024-05-26 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0016_alter_user_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 8, 6, 34, 322299), help_text='Designates the joined date and time of the user.', verbose_name='Joined Date'),
        ),
    ]
