# Generated by Django 5.0.6 on 2024-07-23 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0019_alter_user_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='goal',
            field=models.CharField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 11, 12, 24, 646196), help_text='Designates the joined date and time of the user.', verbose_name='Joined Date'),
        ),
    ]
