# Generated by Django 5.0.6 on 2024-07-23 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0020_badge_goal_alter_user_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 20, 5, 44, 80868), help_text='Designates the joined date and time of the user.', verbose_name='Joined Date'),
        ),
        migrations.AlterModelTable(
            name='badge',
            table='auth_badge',
        ),
    ]
