# Generated by Django 5.0.6 on 2025-03-07 04:57

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0021_alter_user_joined_date_alter_badge_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_icon',
            field=models.ImageField(upload_to='badges/', verbose_name='Badge Icon'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Badge Name'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='goal',
            field=models.CharField(blank=True, default=0, verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notificationtype',
            field=models.CharField(choices=[('post', 'Post'), ('announcement', 'Announcement'), ('activity', 'Activity'), ('post_valid', 'Post Validated'), ('achievement', 'Achievement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=65, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=65, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 12, 57, 53, 393671), verbose_name='Joined Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=65, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='profiles/default.png', null=True, upload_to='profiles', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='is_contributor',
            field=models.BooleanField(default=False, verbose_name='Contributor'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Officer'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Administrator'),
        ),
    ]
