# Generated by Django 5.0.4 on 2024-06-16 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0037_alter_account_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether the user should be considered active or not.', verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 16, 10, 36, 1, 54837), help_text='Designates the joined date and time of the user.', verbose_name='Joined Date'),
        ),
    ]
