# Generated by Django 5.0.4 on 2024-06-16 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0041_alter_user_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_photo',
            field=models.ImageField(default='profiles/default.png', help_text='Designates the valid ID of the user.', null=True, upload_to='cards', verbose_name='Valid ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 16, 14, 43, 27, 218039), help_text='Designates the joined date and time of the user.', verbose_name='Joined Date'),
        ),
    ]
