# Generated by Django 5.0.4 on 2024-05-18 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliaries', '0001_initial'),
        ('managements', '0004_alter_intervention_intervention_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Designates the foreign key of the Location model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='managements.location', verbose_name='Location'),
        ),
    ]
