# Generated by Django 5.0 on 2023-12-27 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Designates the title of the announcement.', max_length=150, verbose_name='Title')),
                ('context', models.TextField(help_text='Designates the context of the announcement.', max_length=5000, null=True, verbose_name='Context')),
                ('place', models.CharField(help_text='Designates the place of the announcement.', max_length=150, verbose_name='Place')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Designates the date and time of the post.', verbose_name='Date')),
                ('user', models.ForeignKey(blank=True, help_text='Designates the foreign field of the User model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentications.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'auxiliaries_announcement',
            },
        ),
    ]
