# Generated by Django 5.0 on 2024-03-25 12:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Designates the name of the author.', max_length=150, verbose_name='Author')),
                ('title', models.CharField(help_text='Designates the title of the resource.', max_length=150, verbose_name='Title')),
                ('release_date', models.DateTimeField(default=datetime.datetime.now, help_text='Designates the release date and time of the resource.', verbose_name='Release Date')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'db_table': 'auxiliaries_resource',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Designates the title of the announcement.', max_length=150, verbose_name='Title')),
                ('context', models.TextField(help_text='Designates the context of the announcement.', max_length=5000, verbose_name='Context')),
                ('place', models.CharField(help_text='Designates the place of the announcement.', max_length=150, verbose_name='Place')),
                ('release_date', models.DateTimeField(default=datetime.datetime.now, help_text='Designates the release date and time of the announcement.', verbose_name='Release Date')),
                ('announcement_photo', models.ImageField(default='announcements/default.png', help_text='Designates the photo of the announcement.', null=True, upload_to='announcements', verbose_name='Announcement Photo')),
                ('user', models.ForeignKey(help_text='Designates the foreign key of the User model.', on_delete=django.db.models.deletion.CASCADE, to='authentications.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'auxiliaries_announcement',
            },
        ),
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_file', models.FileField(help_text='Designates the file of the resource.', upload_to='resources', verbose_name='Resource File')),
                ('resource', models.ForeignKey(help_text='Designates the foreign key of the Resource model.', on_delete=django.db.models.deletion.CASCADE, to='auxiliaries.resource', verbose_name='Resource')),
            ],
            options={
                'verbose_name': 'Resource File',
                'verbose_name_plural': 'Resource Files',
                'db_table': 'auxiliaries_resource_file',
            },
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_link', models.CharField(help_text='Designates the link of the resource.', max_length=2050, verbose_name='Resource Link')),
                ('resource', models.ForeignKey(help_text='Designates the foreign key of the Resource model.', on_delete=django.db.models.deletion.CASCADE, to='auxiliaries.resource', verbose_name='Resource')),
            ],
            options={
                'verbose_name': 'Resource Link',
                'verbose_name_plural': 'Resource Links',
                'db_table': 'auxiliaries_resource_link',
            },
        ),
    ]
