# Generated by Django 5.0 on 2024-03-01 00:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Designates the title of the announcement.', max_length=150, verbose_name='Title')),
                ('context', models.TextField(help_text='Designates the context of the announcement.', max_length=5000, null=True, verbose_name='Context')),
                ('place', models.CharField(help_text='Designates the place of the announcement.', max_length=150, verbose_name='Place')),
                ('release_date', models.DateTimeField(default=datetime.datetime.now, help_text='Designates the release date and time of the announcement.', verbose_name='Release Date')),
                ('announcement_photo', models.ImageField(blank=True, default='announcements/default.png', help_text='Designates the photo of the announcement.', null=True, upload_to='announcements', verbose_name='Announcement Photo')),
                ('user', models.ForeignKey(blank=True, help_text='Designates the foreign key of the User model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentications.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'auxiliaries_announcement',
            },
        ),
    ]
