# Generated by Django 5.0 on 2024-03-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Designates the question of the inquiry.', max_length=150, verbose_name='Question')),
                ('answer', models.TextField(help_text='Designates the answer of the inquiry.', max_length=5000, verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'db_table': 'auxiliaries_inquiry',
            },
        ),
    ]
