# Generated by Django 5.0.4 on 2024-06-24 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='author',
            field=models.CharField(max_length=150, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='file',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='file',
            name='resource_file',
            field=models.FileField(upload_to='resources', verbose_name='Resource File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='answer',
            field=models.TextField(max_length=5000, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='question',
            field=models.CharField(max_length=150, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='link',
            name='author',
            field=models.CharField(max_length=150, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='link',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='link',
            name='resource_link',
            field=models.CharField(max_length=2050, verbose_name='Resource Link'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
