# Generated by Django 5.0.4 on 2024-06-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliaries', '0002_announcement_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='hosting_agency',
            field=models.CharField(blank=True, help_text='Designates the name of the hosting agency.', max_length=150, null=True, verbose_name='Hosting Agency'),
        ),
    ]
