# Generated by Django 5.0.4 on 2024-06-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliaries', '0003_announcement_hosting_agency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
