# Generated by Django 5.0.4 on 2024-06-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliaries', '0004_delete_resource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Links',
        ),
    ]
