# Generated by Django 5.0.4 on 2024-06-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliaries', '0006_rename_links_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
