# Generated by Django 5.0.4 on 2024-06-04 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliaries', '0007_delete_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Designates the title of the resource link.', max_length=150, verbose_name='Title')),
                ('resource_link', models.CharField(help_text='Designates the link of the resource.', max_length=2050, verbose_name='Resource Link')),
                ('release_date', models.DateTimeField(default=datetime.datetime.now, help_text='Designates the release date and time of the resource link.', verbose_name='Release Date')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'db_table': 'auxiliaries_link',
            },
        ),
    ]
