# Generated by Django 5.0.4 on 2024-06-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliaries', '0008_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
