# Generated by Django 5.0.4 on 2024-06-04 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliaries', '0009_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Designates the title of the resource file.', max_length=150, verbose_name='Title')),
                ('resource_file', models.FileField(help_text='Designates the file of the resource.', upload_to='resources', verbose_name='Resource File')),
                ('release_date', models.DateTimeField(default=datetime.datetime.now, help_text='Designates the release date and time of the resource file.', verbose_name='Release Date')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'db_table': 'auxiliaries_file',
            },
        ),
    ]
