# Generated by Django 5.0.6 on 2024-06-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliaries', '0010_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='author',
            field=models.CharField(help_text='Designates the name of the author.', max_length=150, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='link',
            name='author',
            field=models.CharField(help_text='Designates the name of the author.', max_length=150, null=True, verbose_name='Author'),
        ),
    ]
