# Generated by Django 5.0.6 on 2024-06-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliaries', '0011_file_author_link_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Resource File', 'verbose_name_plural': 'Resource File'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Resource Link', 'verbose_name_plural': 'Resource Link'},
        ),
    ]
