# Generated by Django 5.0.4 on 2024-06-16 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliaries', '0012_alter_file_options_alter_inquiry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Designates the creation date and time of the announcement.', verbose_name='Creation Date'),
        ),
    ]
