# Generated by Django 5.0.4 on 2024-05-16 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_post_capture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='capture_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 10, 21, 40, 299876), help_text='Designates the capture date and time of the post.', verbose_name='Capture Date'),
        ),
    ]
