# Generated by Django 5.0.4 on 2024-05-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_post_read_date_post_read_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contrib_read_date',
            field=models.DateTimeField(blank=True, help_text='Designates the date and time when the post was read by a contributor.', null=True, verbose_name='Contributor Read Date'),
        ),
        migrations.AddField(
            model_name='post',
            name='contrib_read_status',
            field=models.BooleanField(default=False, help_text='Indicates whether the post has been read by a contributor.', verbose_name='Contributor Read Status'),
        ),
    ]
