# Generated by Django 5.0.4 on 2024-05-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_depth_is_profound'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='remarks',
            field=models.CharField(blank=True, help_text='Additional remarks for the post.', max_length=255, null=True, verbose_name='Remarks'),
        ),
    ]
